  3 2 1
8 O O O
7      
6     O
5      
4      
-------             add     a
3 O    
2 O    
1 O    
8 O O O
7      
6     O
5     O
4   O  
-------             rar     #2
3     O
2 O   O
1 O   O
8 O O O
7      
6     O
5     O
4   O  
-------             ral     #2
3     O
2 O   O
1 O    
8 O O O
7      
6   O O
5     O
4   O  
-------             sar     #2
3     O
2 O   O
1 O   O
8 O O O
7      
6   O O
5     O
4   O  
-------             sal     #2
3     O
2 O   O
1 O    
8 O O O
7      
6     O
5     O
4     O
-------             hlt
3   O O
2     O
1      
8 O O O
7      
6 O O O
5 O O O
4 O O O
------- negone:     .fill   -1
3 O O O
2 O O O
1   O O
8 O O O
7      
6 O    
5 O    
4      
------- a:          .fill   370
3   O  
2 O    
1   O  
8 O O O
7      
6 O O  
5 O O  
4 O O O
------- b:          .fill   65535
3 O O O
2 O O O
1 O O O
